import Home from './home'
import Insurance from './insurance'
import Detail from './detail'
import selectAddress from './selectAddress'
import Quoted from './quoted'
import List from './list'
import Confirm from './confirm'
import Edit from './edit'
import Process from './process'
import phoneList from './phoneList'
import Reserve from './reserve'
import services from './services'
import myService from './myService'
import businessList from './businessList'
import useranalysis from './useranalysis'

export default Object.assign({}, Home, Insurance, Detail, selectAddress, Quoted, List, Confirm, Edit, Process, phoneList, Reserve, services, myService, businessList, useranalysis)
